2025-04-22 16:31:03,762 - INFO - products.xlsx fayli topildi, CSV ga aylantirilmoqda...
2025-04-22 16:31:04,144 - INFO - products.xlsx fayli products.csv ga aylantirildi.
2025-04-22 16:31:04,656 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: wrong HTTP URL specified
2025-04-22 16:31:04,659 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Minato\AppData\Local\Programs\Python\Python312\Lib\site-packages\telebot\__init__.py", line 1235, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\Users\Minato\AppData\Local\Programs\Python\Python312\Lib\site-packages\telebot\util.py", line 150, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Minato\AppData\Local\Programs\Python\Python312\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\Minato\Desktop\telegram  bot\bot.py", line 394, in search_by_customer_code
    bot.send_sticker(message.chat.id, SUCCESS_STICKER)
  File "C:\Users\Minato\AppData\Local\Programs\Python\Python312\Lib\site-packages\telebot\__init__.py", line 2794, in send_sticker
    apihelper.send_data(
  File "C:\Users\Minato\AppData\Local\Programs\Python\Python312\Lib\site-packages\telebot\apihelper.py", line 1089, in send_data
    return _make_request(token, method_url, params=payload, files=files, method='post')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Minato\AppData\Local\Programs\Python\Python312\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Minato\AppData\Local\Programs\Python\Python312\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: wrong HTTP URL specified

2025-04-22 16:31:33,069 - INFO - products.csv fayli topildi, o'qilmoqda...
2025-04-22 16:31:33,076 - INFO - CSV fayl muvaffaqiyatli o'qildi.
2025-04-22 16:31:33,351 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: wrong HTTP URL specified
2025-04-22 16:31:33,355 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Minato\AppData\Local\Programs\Python\Python312\Lib\site-packages\telebot\__init__.py", line 1235, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\Users\Minato\AppData\Local\Programs\Python\Python312\Lib\site-packages\telebot\util.py", line 150, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Minato\AppData\Local\Programs\Python\Python312\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\Minato\AppData\Local\Programs\Python\Python312\Lib\site-packages\telebot\__init__.py", line 9233, in _run_middlewares_and_handler
    result = handler['function'](message)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Minato\Desktop\telegram  bot\bot.py", line 421, in handle_message
    search_by_customer_code(message)
  File "C:\Users\Minato\Desktop\telegram  bot\bot.py", line 394, in search_by_customer_code
    bot.send_sticker(message.chat.id, SUCCESS_STICKER)
  File "C:\Users\Minato\AppData\Local\Programs\Python\Python312\Lib\site-packages\telebot\__init__.py", line 2794, in send_sticker
    apihelper.send_data(
  File "C:\Users\Minato\AppData\Local\Programs\Python\Python312\Lib\site-packages\telebot\apihelper.py", line 1089, in send_data
    return _make_request(token, method_url, params=payload, files=files, method='post')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Minato\AppData\Local\Programs\Python\Python312\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Minato\AppData\Local\Programs\Python\Python312\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: wrong HTTP URL specified

